---
- name: "Consul config: Create directory"
  file:
    path: /var/lib/micado/consul/config/
    state: directory
    mode: 0775
    recurse: yes
- name: "Consul config: Copy file"
  copy:
    src: consul/config.json
    dest: /var/lib/micado/consul/config/config.json
    mode: 0644
- name: "Consul config: create checks.json"
  template:
    src: consul/checks.json.j2
    dest: /var/lib/micado/consul/config/checks.json
    mode: 0644

- name: "Prometheus config: Create directory"
  file:
    path: /var/lib/micado/prometheus/config/
    state: directory
    mode: 0775
    recurse: yes
- name: "Prometheus config: Copy file"
  copy:
    src: prometheus/prometheus.yml
    dest: /var/lib/micado/prometheus/config/prometheus.yml
    mode: 0644

- name: "Alertmanager config: Create directory"
  file:
    path: /var/lib/micado/alertmanager/config/
    state: directory
    mode: 0775
    recurse: yes
- name: "Alertmanager config: Copy file"
  copy:
    src: alertmanager/config.yml
    dest: /var/lib/micado/alertmanager/config/config.yml
    mode: 0644

- name: "Policy-keeper config: Create directory"
  file:
    path: /var/lib/micado/policykeeper/config/
    state: directory
    mode: 0775
    recurse: yes
- name: "Policy-keeper: Copy config file"
  template:
    src: policykeeper/policykeeper_config.yaml.j2
    dest: /var/lib/micado/policykeeper/config/policykeeper_config.yaml
- name: "Policy-keeper: Copy prometheus file"
  copy:
    src: policykeeper/prometheus_config_template.yaml
    dest: /var/lib/micado/policykeeper/config/prometheus_config_template.yaml
    mode: 0644

- name: "Grafana config: Create config directory"
  file:
    path: /var/lib/micado/grafana/config/
    state: directory
    mode: 0775
    recurse: yes
- name: "Grafana config: Copy server config file"
  copy:
    src: grafana/grafana.ini
    dest: /var/lib/micado/grafana/config/grafana.ini
    mode: 0644
- name: "Grafana config: Create dashboard directory"
  file:
    path: /var/lib/micado/grafana/data/dashboards
    state: directory
    mode: 0775
    recurse: yes
- name: "Grafana config: Copy dashboard file"
  copy:
    src: grafana/data-dashboards-micado.json
    dest: /var/lib/micado/grafana/data/dashboards/micado.json
    mode: 0644
- name: "Grafana config: Create dashboard providers directory"
  file:
    path: /var/lib/micado/grafana/provisioning/dashboards
    state: directory
    mode: 0775
    recurse: yes
- name: "Grafana config: Copy dashboard provider file"
  copy:
    src: grafana/provisioning-dashboards-provider.yaml
    dest: /var/lib/micado/grafana/provisioning/dashboards/provider.yaml
    mode: 0644
- name: "Grafana config: Create datasource directory"
  file:
    path: /var/lib/micado/grafana/provisioning/datasources
    state: directory
    mode: 0775
    recurse: yes
- name: "Grafana config: Copy datasource file"
  copy:
    src: grafana/provisioning-datasources-prometheus.yaml
    dest: /var/lib/micado/grafana/provisioning/datasources/prometheus.yaml
    mode: 0644

- name: "TOSCAsubmitter config: Create working directory"
  file:
    path: /var/lib/micado/toscasubmitter/system
    state: directory
    mode: 0775
    recurse: yes
- name: "TOSCAsubmitter config: Copy config file"
  copy:
    src: toscasubmitter/key_config.yml
    dest: /var/lib/micado/toscasubmitter/system/key_config.yml
    mode: 0644

- name: "Zorp config: Create directory"
  file:
    path: /var/lib/micado/zorp/config/
    state: directory
    mode: 0775
    recurse: yes
- name: "Zorp config: Copy file"
  copy:
    src: zorp/policy.py
    dest: /var/lib/micado/zorp/config/policy.py
    mode: 0644
- name: "Zorp HTTP login form: Copy file"
  copy:
    src: zorp/authform.html
    dest: /var/lib/micado/zorp/config/authform.html
    mode: 0644
- name: "Zorp entrypoint: Create directory"
  file:
    path: /var/lib/micado/zorp/scripts/
    state: directory
    mode: 0775
    recurse: yes
- name: "Zorp entrypoint: Copy file"
  copy:
    src: zorp/zorp-entrypoint.sh
    dest: /var/lib/micado/zorp/scripts/docker-entrypoint.sh
    mode: 0755
- name: Create user_data_zorp.env for Zorp
  template:
      src: user_data/user_data_zorp.env.j2
      dest: "/var/lib/micado/zorp/config/user_data_zorp.env"

- name: "Docker-compose: Copy file"
  template:
    src: docker/docker-compose.yml.j2
    dest: /var/lib/micado/docker-compose.yml
    mode: 0644
