---
- name: "Disable updates"
  script: files/misc/disable-updates.sh

# TODO: Configure hostname here

- name: Load the credentials and security settings from the playbook
  include_vars:
    file: "credentials.yml"
    name: config

- name: 'Installing packages'
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https # TODO: Docker part will install this
    - ca-certificates # TODO: Docker part will install this
    - curl 
    - software-properties-common 
    - wget 
    - unzip 
    - jq 
    - dnsmasq

- name: 'Installing mictl dependencies'
  pip:
    name:
      - requests
      - click
      - terminaltables
    state: present

# FIXME: Why do we need this?
- name: 'Create Prometheus user'
  user:
    name: prometheus
    createhome: no
    state: present

- include: docker-install.yml

- include: files.yml

- include: worker_node.yml

- include: docker-pull-images.yml

- name: "Run runcmd.sh script #FIXME"
  script: files/misc/runcmd.sh
