---
- name: "Disable updates"
  script: files/misc/disable-updates.sh

- name: Ensure Google DNS server added
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 8.8.8.8'

- name: Change hostname
  hostname:
    name: "{{ micado_master_name }}"

- name: Ensure that the hostfile contains the actual hostname
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1\tlocalhost\t{{ micado_master_name }}"

- name: Load the credentials and security settings from the playbook
  include_vars:
    file: "credentials.yml"
    name: config

- name: 'Installing packages'
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https # TODO: Docker part will install this
    - ca-certificates # TODO: Docker part will install this
    - curl 
    - software-properties-common 
    - wget 
    - unzip 
    - jq 
    - dnsmasq

- name: 'Installing mictl dependencies'
  pip:
    name:
      - requests
      - click
      - terminaltables
    state: present

- include: docker-install.yml

- include: files.yml

- include: worker_node.yml

- include: docker-pull-images.yml

- include: start_micado.yml
