---
- include: setup-master-node.yml

- include: docker-install.yml
  when: not ci

- include: files.yml

- include: worker_node.yml
  when: not ci

- include: docker-pull-images.yml

- include: start_micado.yml

- include: docker-login.yml
  when: docker_cred_path is defined
