version: 2
jobs:
  test:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run: pwd
      - run: ls -al
      - run: sudo apt-get update -qq
      - run: sudo sudo apt-get install -y sshpass software-properties-common python-software-properties
      - run: sudo apt-add-repository -y ppa:ansible/ansible
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -y ansible
      - run: sudo ansible-playbook -i sample_hosts micado-master.yml --syntax-check

  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker-compose --version
      - run: docker-compose -f testing/circleci/docker-compose.yml pull
      - run: docker-compose -f testing/circleci/docker-compose.yml up -d
      - run: docker ps
      - run: docker-compose -f testing/circleci/docker-compose.yml logs
      - run: sleep 10
      - run: curl --insecure https://admin:password@127.0.0.1/docker-visualizer
      - run: curl --insecure https://127.0.0.1/docker-visualizer
      - run:
          name: Show docker logs on failure
          command: docker-compose -f testing/circleci/docker-compose.yml logs
          when: on_fail

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
